import type {Metadata} from "next";
import {Geist, Geist_Mono, Vazirmatn} from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/header";
import Footer from "@/components/layouts/footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const vazirMatn = Vazirmatn({
    variable: "--font-vazir",
    subsets: ["arabic"],
});

export const metadata: Metadata = {
    title: "نمایندگی 777",
    description: "Generated by create next app",
};

export default function RootLayout({children}: LayoutProps<"/">) {
    return (
        <html
            lang="fa" dir="rtl"
            className={`${vazirMatn.className} h-full antialiased`}>
        <body className="min-h-full bg-slate-50">
        <Header />
        {children}
        <Footer />
        </body>
        </html>
    );
}
